# 主题设置
theme: jekyll-theme-hacker

# 网站基础信息
title: 我的知识库 | YHR
description: YOLO 你只活一次 | YHR

# ===================================================================
# 关键配置：这是项目站点的标准配置，请勿修改！
# ===================================================================
# 您的GitHub Pages域名 (末尾没有斜杠)
url: "https://1184330889.github.io"  
# 您的仓库名 (前面必须有斜杠 "/")
baseurl: "/-.github.io"             

# ===================================================================
# 永久链接 (Permalink) 设置
# ===================================================================
# 这个设置决定了您文章链接的格式，它会把分类名(如"思考")加入URL
permalink: /:categories/:year/:month/:day/:title.html
