# 网站配置
title: "你的网站标题"
description: "你的网站描述"
baseurl: ""
url: "https://你的域名.com"
permalink: /:year/:month/:day/:title/

# 作者配置
author:
  name: "你的名字"
  email: "你的邮箱"
  bio: "你的个人简介"
  avatar: "/assets/avatar.jpg"

# 社交链接
social:
  github: "你的GitHub用户名"
  twitter: "你的Twitter用户名"
  weibo: "你的微博用户名"
  rss: true

# 布局配置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# 插件配置
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-commonmark-ghpages
  - jekyll-include-cache

# 分页配置
paginate: 10
paginate_path: "/page/:num/"

# 预处理器配置
markdown: CommonMark
highlighter: rouge

# 语言配置
lang: zh-CN
