# 主题设置
theme: jekyll-theme-hacker

# 网站基础信息
title: 我的知识库 | YHR
description: YOLO 你只活一次 | YHR

# ===================================================================
# 关键配置：这是项目站点的标准配置，请勿修改！
# (确保每一行末尾都没有多余的空格)
# ===================================================================
url: "https://1184330889.github.io"
baseurl: "/-.github.io"

# ===================================================================
# 永久链接 (Permalink) 设置
# ===================================================================
permalink: /:categories/:year/:month/:day/:title.html
