source 'https://rubygems.org'
gem 'jekyll', '~> 4.2'
gem 'jekyll-paginate'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'jekyll-gist'
gem 'jekyll-coffeescript'
gem 'jekyll-avatar'
gem 'jekyll-redirect-from'
gem 'jekyll-commonmark-ghpages'
gem 'jekyll-include-cache'
