site_name: 浩然的知识库
site_description: 每日计划 · 反思 · 灵感 · 收藏
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - search.highlight
    - search.suggest
    - content.code.copy
    - tags
  palette:
    - scheme: slate
      primary: indigo
      accent: deep purple
plugins:
  - search
  - tags
  - glightbox
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - tables
  - def_list
  - attr_list
extra:
  social:
    - icon: material/github
      link: https://github.com/1184330889
nav:
  - 首页: index.md
  - 每日: 
    - 2025/08/11: daily/2025/08/11.md
  - 反思: reflections/index.md
  - 知识卡: notes/index.md
  - 收藏: favorites/index.md
  - 标签索引: tags.md
